### PR TITLE
[compute] Port DigitalOcean provider to APIv2.

### PR DESCRIPTION
**Pull request by andrewsomething**
DigitalOcean's APIv1 has been deprecated for some time, and it is [planned to be shut off on November 9th](https://developers.digitalocean.com/documentation/changelog/api-v1/sunsetting-api-v1/). This branch is a port to APIv2.

pkgcloud abstracts enough away that it should be a fairly easy transition in most cases. The big difference is  the clientID/key pair is now an OAuth token. On creates, `size_id` and `image_id` have been replaced with "slugs."

### CODE REVIEW

**Comment by indexzero** [comment]
@andrewsomething awesome!

**Comment by andrewsomething** [comment]
If anyone has gotten a chance to test, I'd love any feedback. Be great if this landed before v1 is shut off.

**Comment by indexzero** [comment]
TravisCI passes. I'm good with that. @kenperkins @rosskukulinski?

**Comment by rgbkrk** [comment]
:shipit:

**Comment by indexzero** [comment]
I want to land this, but currently we are in a weird release state. Once https://github.com/pkgcloud/pkgcloud/pull/475 lands I'll make sure this is the #1 priority for merging. Will be `pkgcloud@1.3.0`

**Pull request merged**
