### PR TITLE
[WIP] [dns] dnsimple Initial Working version

### PR DESCRIPTION
**Pull request by tomgco**
- getZones
- getRecords
- getRecord, updateRecord, deleteRecord
- Cleanup and return errors on non implemented methods

Currently missing zone bulk methods, zone import and tests.

### CODE REVIEW

**Comment by kenperkins** [comment]
Closing this until someone picks it back up.

**Comment by indexzero** [comment]
@kenperkins can we create a tag for these "abandoned" pull requests? Would like to keep track of things other folks _could_ pick back up if they wanted to.

**Comment by indexzero** [comment]
Or is that just the `not-ready` tag that already exists?

**Comment by kenperkins** [comment]
I'm open to either. Just tired of the noise.

**Pull request closed without merging**
