### PR TITLE
[fix] Patched RegEx DoS vuln & Remote Memory Exposure vuln

### PR DESCRIPTION
**Pull request by rgeraldporter**
This addresses two major security issues:

https://nodesecurity.io/advisories/309
https://nodesecurity.io/advisories/535

First, a note: before adding this commit, master branch had 18 failing tests. I've ensured that after this commit the same 18 tests are failing, and not any different ones.

This patch addresses vulnerabilities with `mime` and `request` modules being used.

`mime` v1.x was recently discovered to be vulnerable to a RegEx Denial-of-Serice attack. This has two vectors within `pkgcloud` as it includes `mime` directly, and the old version of `request` being pinned is also using a vulnerable version of `mime`.

`request` also had its own vulnerability, a Remote Memory Exposure vulnerability.

Unfortunately just updating the versions on these resulted in more failing tests. The test dependency, `hock`, does not work as expected with `request` v2.83.0 due to some differences with how it expects JSON to be exposed for pattern matching. I've adjusted the tests with a workaround (heavy escaping), however I will also submit a pull request to the `hock` repository with a fix for this.

### CODE REVIEW

**Comment by rgeraldporter** [comment]
@BobDickinson can we get this merged? Do you need more team members here?

**Comment by rosskukulinski** [comment]
published as 1.5.0

**Comment by rosskukulinski** [comment]
@rgeraldporter I have also given you commit rights to pkgcloud.  There will likely be one or two more new contribs in the next week.  I'll hold onto npm publish rights until things have stabilized and everyone trusts the new folks :)

**Comment by NicolaiSchmid** [comment]
I really appreciate, this project getting a bit of maintenance!

**Comment by rgeraldporter** [comment]
Thanks Ross!

**Pull request merged**
