### PR TITLE
[WIP] Image creation on DO (and all dependencies)

### PR DESCRIPTION
**Pull request by mmalecki**
This includes:

  * image creation
  * server shutdown (needed to create an image)
  * async request handling (event polling)

### CODE REVIEW

**Comment by kenperkins** [comment]
Closing this until someone picks it back up.

**Comment by stuartpb** [comment]
I'll take a look at this.

**Comment by stuartpb** [comment]
For my purposes, I'd rather have some kind of way to just get the event ID to let clients poll on their own, rather than having the callback do it.

**Comment by kenperkins** [comment]
I think you're talking about the difference between abstracting away multiple calls, versus not? Maybe we can do both? Maybe `createImage` is the full encapsulated version, where perhaps `createImageJob` or something to that effect only returns the async status id?

**Pull request closed without merging**
