### PR TITLE
Replace underscore for lodash

### PR DESCRIPTION
**Pull request by underbyte**
This pr is an attempt to replace underscore for lodash per request #413. The only major change was the usage of `_.template`, lodash required that the template be compiled first then a second call to pass in the parameters.

Note: master currently has one broken test (so I don't expect this branch to fully work)

### CODE REVIEW

**Comment by underbyte** [comment]
@kenperkins any interest in PR or should I close?

**Comment by kenperkins** [comment]
I completely agree with removing underscore. Let me review.

**Comment by kenperkins** [comment]
:+1:

**Comment by kenperkins** [comment]
I should have checked this out local before I merged, but it was an easy fix.

**Pull request merged**
