### PR TITLE
Pre-release: 2.x

### PR DESCRIPTION
**Pull request by indexzero**
- Updates all dependencies (with passing tests thanks to @ClaudiuOctavianMuresan in #654).
- Removes legacy providers.

@rosskukulinski @jcrugzz could one of you give this a look over and 👍?

### CODE REVIEW

**Comment by rachedanis** [comment]
Hello, can you please communicate the release date ? Thanks

**Comment by VerrNum** [comment]
please we need also this change, thank you

**Comment by rachedanis** [comment]
+1

**Comment by rachedanis** [comment]
Hello @indexzero, thank you for this contribution ! 
But why it's not merged yet ?

**Pull request merged**
