### PR TITLE
Amazon storage use native aws-sdk for uploads

### PR DESCRIPTION
**Pull request by fogine**
* Update the aws-sdk
* Use `upload` method of native `aws-sdk` rather than external `s3-upload-stream` module
* expose concurrency - `queueSize` and `partSize` configurability for the `client.upload` method
* expose `managedUpload` object on returned stream which provides ability to abort upload or track upload progress
* Fixed download/upload tests for large files which have been  skipped till now.

Due to `aws-sdk`'s weird design, extra processing steps had to be added to preserve `client.upload` method behavior. (I refer to two proxy streams used in the `upload` method). 
Certainly not good solution... however it seems there is no better one. 

Some download/upload test tweaks had to be made due to behavior of `aws-sdk`'s `upload` method which makes one `putObject` request if an object being uploaded is not large enough. if the object size exceeds defined `partSize`, it uses multipart upload API.

### CODE REVIEW

**Comment by fogine** [comment]
Those two failing tests also fails locally on master with fresh repo clone (they are not subject of this PR).
Added large file upload/download tests fails on node 0.10 but passes on node 6.8. I've not found the issue thus the tests are skipped for `azure` for now.

**Comment by fogine** [comment]
ping @kenperkins , @BobDickinson, @indexzero , @rosskukulinski 

Don't wan't to be rude or anything, I understand the "flaws" of opensource. It seems the library is no longer maintained as main actors of this project no longer have time for it or lost interest...?
May I ask whether you plan to spend some time on this project (in near future) ? What's the status of this project?

Also I wanna express my gratitude for your contributions to the open source! Thank you for sharing your work!

**Comment by rosskukulinski** [comment]
@fogine sorry!  I can't speak for the others, but I haven't personally used pkgcloud in over a year.  We on-boarded @BobDickinson as a contributor, but things have been rather quiet.

I'm all for bringing new contributors on board if you're interested and using this project.

Regarding your PR - I pushed a fix for the broken test to `master`.  If you merge in master your PR tests should all pass.  Diff looks good.  Do we need to update any documentation?

**Comment by fogine** [comment]
@rosskukulinski , thanks for quick response and for the fix. There isn't any documentation that can be updated so I've added brief doc section about amazon file uploads.

As for my future contributions - I've stumbled upon this project quite recently thus I'm still not sure whether to include it in production. However I'd gladly provide PRs for my upcoming issues... like adding support for `headers` option when initiating a s3 upload and possibly others. But I would need to know there is someone I can connect (communicate) with in regard of future PRs.  I see quite few PRs are hanging in air for too long. I would not want waste my time.

Thanks.

**Comment by BobDickinson** [comment]
@fogine Speaking only for myself, I have been lazier here than I intended.  We use pkgcloud in our product https://github.com/SynchroLabs/SynchroServer and in another project https://github.com/SynchroLabs/StashBox

I came on as a contributor to fix one specific issue (OpenStack storage on BlueMix), and since I wanted to get that into a published NPM release, I went through and took all of the non-controversial PRs, and a couple of higher priority PRs that took some review (and where I pulled in some other contributors), update the release notes, and worked with @indexzero to get the release done.

I think in my case, going forward, I'm not likely to be super proactive (go deep diving to research and fix issues).  But I am happy to work with people who submit PRs, and help get releases out (I'd much rather someone who is using the backend service and knows the SDK do the fixes).  That being said, triage could be better (when I see the "someone should go implement this mode of that provider" type of issue, I just kind of say to myself "yes, someone should do that").

I'll try to do a better job of staying on top of PRs.  I think in general this seems to be the kind of project where a PR has a much, much better chance of being addressed than a issue (at least by me).

**Comment by jcrugzz** [comment]
Will be cherry picking  this with some minor changes, thanks @fogine

**Pull request merged**
