### PR TITLE
Fixes request@2.40.x has another vulnerability

### LINKED ISSUE #573: request@2.40.x has another vulnerability
nsp check:
```
Remote Memory Exposure
Name: request
Installed: 2.40.0
Vulnerable: >=2.2.6 <2.47.0 || >2.51.0 <=2.67.0
Patched: >= 2.68.0
```
https://nodesecurity.io/advisories/309

Upgrading the request package to >=2.70.0 should also resolve this:
https://github.com/pkgcloud/pkgcloud/issues/542

### PR DESCRIPTION
**Pull request by dyaa**
Fixes #573

Please check this https://nodesecurity.io/advisories/309

---
This change is [Reviewable](https://reviewable.io/reviews/pkgcloud/pkgcloud/574)

### CODE REVIEW

**Comment by TimPerry** [comment]
Could we get this merged? Are the CI issues legit?

**Comment by dyaa** [comment]
@Vooodoo can you push it to `npm` ?

**Comment by monsty** [comment]
Can someone merge this PR ?

**Comment by mattgrande** [comment]
I'm starting to worry that this project's been abandoned... No merges since Feb 2.

**Comment by shenghu** [comment]
@Vooodoo can this pr be fixed and merged. The vulnerability issue becomes a blocker for us.

**Comment by rgeraldporter** [comment]
I also have a fix for this on #587 that also fixes the unit tests that this change breaks.

**Comment by rosskukulinski** [comment]
Resolved in #587

**Pull request closed without merging**
