### PR TITLE
Land 1.2.0

### PR DESCRIPTION
**Pull request by indexzero**
Supercedes #474

### CODE REVIEW

**Comment by indexzero** [comment]
@kenperkins would like get this in so that we can land #470 cleanly.

**Comment by josiasmontag** [comment]
Ping! Would love to use pkgcloud, but there are some bad bugs which seem to be fixed by various PRs. Any chance to get this merged?

**Comment by indexzero** [comment]
This has aged on the vine but the tests pass so let's do it.

**Comment by josiasmontag** [comment]
Thanks!

**Pull request merged**
