### PR TITLE
[compute] Compute Service with tests

### PR DESCRIPTION
**Pull request by alibazlamit**
1&1 Compute Service that includes Servers, Images and Flavors.

### CODE REVIEW

**Comment by rosskukulinski** [comment]
Hi @alibazlamit - thanks for the submission!  I took a look at your code & tests and it all looks good.  Could you please add an example to https://github.com/pkgcloud/pkgcloud/tree/master/examples/compute and then add oneandone to the list of providers in the docs (https://github.com/pkgcloud/pkgcloud/tree/master/docs)?

Once that's added I can merge & publish.

**Comment by rosskukulinski** [comment]
Let's just merge them all into one for adding support for 1&1.

**Comment by alibazlamit** [comment]
I have merged all other branches into this one, i think we are good to proceed now.

Thanks

**Comment by alibazlamit** [comment]
@rosskukulinski Just a friendly reminder, could you please take a look at this PR?

Thanks.

**Comment by rosskukulinski** [comment]
Merged after some minor tweaks in #592

**Pull request closed without merging**
