### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by indexzero**
This PR does the following:

- [x] Migrates from `gcloud` to `@google-cloud/storage`.
- [x] Ensures `npm outdated` has zero packages in its output.
- [x] Treats `package-lock.json` as binary in `git` using a `.gitattributes` file.
- [x] **BREAKING** Force `node >= 8.0.0`
- [x] Regenerate `package-lock.json`
- [x] Migrate from `Makefile` to `npm test` 
- [x] Migrate from `blanket` to `nyc` 

### 🐲 Ensures all tests are passing – here be dragons

> **NOTE:** most test failures are from changes to the mocks we use. 

**35 total failing**

- [x] ✅`@google-cloud/storage` – **13 test failures**
- [x] ✅`fast-json-patch` – **5 test failures** within `pkgcloud/openstack/cdn/services`
- [x] ✅`mime` –  **1 test failure** because of [filed#37](https://github.com/mikeal/filed/pull/37). 
   - _Reached out to @mikeal about this. We should remove `filed` eventually, but would prefer not to block this PR on that refactor._
- [x] ✅`through2` – verified causes no additional failures
- [x] ✅`url-join` – **8 test failures** 
- [x] ✅`xml2js` – **8 test failures**

#### Supersedes #535, #554, #610, and #632

### CODE REVIEW

**Comment by indexzero** [comment]
Updated the base to a new `2.x` branch so that #652 and #651 can land together on `master`.

**Comment by ClaudiuOctavianMuresan** [comment]
👍 This is exactly what the community needs.
Yesterday we wanted to drop support for pkgcloud just because it uses gcloud (and not  @google-cloud/storage) and also because of grpc as we ar
But with this PR there is hope 😄 
Is there something we can do to help getting this into master and published?

**Comment by indexzero** [comment]
@ClaudiuOctavianMuresan thanks! As for how you can help: any help fixing the remaining broken tests would be outstanding. Feel free to branch off of this and submit PRs against it.

**Comment by ClaudiuOctavianMuresan** [comment]
I tried to fix the tests and I ended up with remarks/questions:
1. I don't have rights to push my changes on the repository. How should I proceed? Do I need to be added as a contributor?
2. @google-cloud/storage is using gcs-resumable-upload module for "upload" functionality and the url to GCP storage is hard coded therefore I would like to use proxyquire as dev/test dependency. Is this ok with you?
3. The azure tests fixes require updates on the source files. Is this something we can expect? I mean, I adapted the code to work with the existing test fixtures.
4. Dropped"filed" dependency in favor of "filed-mimefix" - until the dependency will be completely removed because of "planned" refactoring
5. Currently we have issues with the upload and download tests from common/storage/base-test because of the google-cloud update (see point 2)

**Comment by rachedanis** [comment]
> I tried to fix the tests and I ended up with remarks/questions:
> 
> 1. I don't have rights to push my changes on the repository. How should I proceed? Do I need to be added as a contributor?
> 2. @google-cloud/storage is using gcs-resumable-upload module for "upload" functionality and the url to GCP storage is hard coded therefore I would like to use proxyquire as dev/test dependency. Is this ok with you?
> 3. The azure tests fixes require updates on the source files. Is this something we can expect? I mean, I adapted the code to work with the existing test fixtures.
> 4. Dropped"filed" dependency in favor of "filed-mimefix" - until the dependency will be completely removed because of "planned" refactoring
> 5. Currently we have issues with the upload and download tests from common/storage/base-test because of the google-cloud update (see point 2)

Hello, as an answer your first question : 
- You have to fork the target repository ( in this case pkgcloud/pkgcloud ) on your profile
- Checkout on the target branch ( in this case fix/dependencies )
- Create your own branch
- Commit your changes on that branch
- Create the Pull request from your own branch of tour fork to the target branch on the target repository

**Comment by ClaudiuOctavianMuresan** [comment]
Thanks @rachedanis 👍

**Pull request merged**
