### PR TITLE
[test] fixes failed tests and uses filed-mimefix instead of filed

### PR DESCRIPTION
**Pull request by ClaudiuOctavianMuresan**

### CODE REVIEW

**Comment by indexzero** [comment]
Thank you for this @ClaudiuOctavianMuresan – will dig into the changes. I'm sure I'll have some questions when I get into the nitty gritty.

**Comment by rachedanis** [comment]
Hello @indexzero, can you please do the code review, we're all waiting for this patch.

**Comment by VerrNum** [comment]
@indexzero yes please :)

**Comment by indexzero** [comment]
FYI latest `filed` has been released, so will revert that portion post-merge

**Comment by indexzero** [comment]
May have spoken too soon there unfortunately as the latest `filed` did not pass the tests. Will continue with `filed-mimefix` for now.

**Pull request merged**
